version: '3.6'
services:

  orthanc:
    image: osimis/orthanc:22.8.0
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    networks:
      - backend
    volumes:
      # configuration file
      - ${ORTHANC_CONFIG}:/etc/orthanc/orthanc.json:ro
      # storage volume for raw dicoms
      - ${ORTHANC_DB_MNT}:/var/lib/orthanc/db
    environment:
      # DICOMWeb Plugin
      - DW_ENABLED=true
      # Postgres Plugin
      - PG_ENABLED=true
    ports:
      - 4242:4242
      - 8042:8042
    command: /etc/orthanc/orthanc.json

  postgres:
    image: postgres:12.1
    container_name: postgres
    networks:
      - backend
    volumes:
      - ${POSTGRES_DATA_MNT}:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=orthanc

networks:
  backend: